version: '3'

services:
  otrs6:
    build: .
    image: otrs:6
    environment:
      APP_DatabaseType: mysql
      APP_DatabaseHost: mysql
      APP_Database: ligero
      APP_DatabaseUser: ligero
      APP_DatabasePw: ligero
      APP_NodeID: 1
      APP_ES_NODE: elastic
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ligero
      MYSQL_DATABASE: ligero
      MYSQL_USER: ligero
      MYSQL_PASSWORD: ligero
    command:
      - --max_allowed_packet=64M
      - --innodb_log_file_size=269331648
      - --query_cache_size=36737518
      - --character_set_server=utf8
      - --bind-address=0.0.0.0
