version: '3'
services:
    nginx:
        image: ligero/otrs:nginx
        #build: .
        environment: 
            - OTRS_CUSTOMER_ID=test
            - OTRS_SYSTEM_ID=10
            - OTRS_DEFAULT_LANGUAGE=pt_BR
            - OTRS_FQDN=${HOSTNAME}
            - OTRS_DATABASE_HOST=mysql
            - OTRS_DATABASE_NAME=otrs
            - OTRS_DATABASE_USER=root
            - OTRS_DATABASE_PASSWORD=xK3MPnLb
            - OTRS_ROOT_PASSWORD=uBpeRvRLZhPPKZsr
        ports:
         - 80:80
        volumes:
         - app:/opt/otrs

    mysql:
        image: mysql:5.7
        volumes:
        - database:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=xK3MPnLb
        - MYSQL_DATABASE=otrs
        command:
        - --max_allowed_packet=64M
        - --innodb_log_file_size=269331648
        - --query_cache_size=36737518
        - --character_set_server=utf8
        - --bind-address=0.0.0.0

volumes:
    database: ~
    app: ~